export enum EPokemonsTypes {
  ALL = 'all',
  NORMAL = 'normal',
  GRASS = 'grass',
  ELECTRIC = 'electric',
  WATER = 'water',
  FIRE = 'fire',
  BUG = 'bug',
  GHOST = 'ghost',
  PSYCHIC = 'psychic',
  STEEL = 'steel',
  DARK = 'dark',
  FLYING = 'flying',
  ICE = 'ice',
  POISON = 'poison',
  GROUND = 'ground',
  ROCK = 'rock',
  DRAGON = 'dragon',
  FIGHTING = 'fighting',
  FAIRY = 'fairy'
}
